/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useSpring, a } from "@react-spring/three";
import { productState } from "../atoms/temps";
import { useRecoilState } from "recoil";





export function Magic(props) {
    const { nodes, materials } = useGLTF("model/Ornament.glb");

    const ornamentRef = useRef();
    const [productname, setProductname] = useRecoilState(productState);

    // Utilisation de useSpring pour animer la rotation
    const { position } = useSpring({
        position: productname!==null ? [0.5, -2.6, -1.5] : [0.5, -6, -1.5], // Rotation complète (2π radians) lorsqu'il est sélectionné
    });

    // Utilisation de useFrame pour mettre à jour la rotation
   

    return (
        <a.group {...props} scale={.000003} position={position} dispose={null} ref={ornamentRef}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder002.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder003.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder004.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder005.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder006.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder007.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder008.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder009.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder010.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder011.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder012.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder013.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder014.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder015.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder016.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder017.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder018.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder019.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder020.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder021.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder022.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder023.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder024.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder025.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder026.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder027.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder028.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder029.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder030.geometry}
                material={materials._crayfishdiffuse}
            ><meshStandardMaterial color={"purple"} emissive="purple" emissiveIntensity={2} toneMapped={false} /></mesh>
        </a.group>
    );
}

useGLTF.preload("model/Ornament.glb");
